# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be441218441c91f925b1ee1cdbc3e06c7a4b4b3ff15e8d2ae880536b0cd24b7c4ffc4cbf8c0ae23e6d9b41d5d232ce9b9ae47a72f9db58cfb93ec62286c93dc5

test:
  secret_key_base: ec4626ec90dad158059d8aa0e861640e72110e0096c94c46588159358cf512d5f15da05eaa78f9d4ecce4bce85c4a549c24790b43878c0be0ee5c7ddfb7ed9c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
